import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const image_size= 32;
  return (
    <div className={styles.container}>
      <Head>
        <title>W3NDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet" /> 
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Welcome traveller. 
        </h1>

        <p className={styles.description}>
          We have projects abound, but here are some of my more enjoyable ones 
        </p>

        <div className={styles.grid}>
          <a 
            href="https://github.com/W3NDO/KilimoShwari-Mobi" 
            className={styles.card}
            target='_blank'
          >
            <h2>Kilimo Shwari &rarr;</h2>
            <h4>
              <Image 
                src="/js.png" 
                width={image_size}
                height={image_size}
              />
            </h4>
            <p>MVP mobile app for a micro Insurance platform!!.</p>
          </a>

          <a 
            href="https://github.com/W3NDO/KilimoShwari-WeatherDataAPI" 
            className={styles.card}
            target='_blank'
          >
            <h2>Kilimo Shwari &rarr;</h2>
            <h4>
              <Image 
                src="/rb.png" 
                width={image_size}
                height={image_size}
              />
            </h4>
            <p>Rails server for a micro Insurance platform!!.</p>
          </a>

          <a 
            href="https://github.com/W3NDO/KilimoShwari-SmartContract" 
            className={styles.card}
            target='_blank'
          >
            <h2>Kilimo Shwari &rarr;</h2>
            <h4>
              <Image 
                src="/ethereum.png" 
                width={image_size}
                height={image_size}
              />
            </h4>
            <p>Smart Contract for a micro Insurance platform in Solidity!!.</p>
          </a>


          <a 
            href="https://github.com/malcolmkiano/swahili" 
            className={styles.card}
            target='_blank'
          >
            <h2>Swahili-Lang &rarr;</h2>
            <h4>
              <Image 
                src="/js.png" 
                width={image_size}
                height={image_size}
              />
            </h4>
            <p>Take a look at this Language I assisted in developing!!.</p>
          </a>

          <a
            href="https://github.com/W3NDO/Organize"
            className={styles.card} 
            target='_blank'
          >
            <h2>File Organisation Script &rarr;</h2>
            <h4>
            <Image 
                src="/sh.png" 
                width={image_size}
                height={image_size}
              />  
            </h4> 
            <p>A script I wrote to organize my downloads folder.</p>
          </a>

          <a
            href="https://github.com/W3NDO/Zipf-s-Law"
            className={styles.card}
            target='_blank'
          >
            <h2>Zipf's law on the Swahili Bible &rarr;</h2>
            <h4> 
              <Image 
                src="/py.png" 
                width={image_size}
                height={image_size}
              />
            </h4>
            <p>
              I analyse the Swahili Bible for Zipf's law using Python.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/W3NDO"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span> Find more on my github Profile</span>
        </a>
      </footer>
    </div>
  )
}
